markdown: kramdown
collections:
  projects:
    output: true

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "case-study"
  - scope:
      path: ""
    values:
      layout: "default"